config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

resources :users, only: [:index, :show] do
    member do
      get 'send_request', to: 'friendships#create'
      get 'accept_request', to: 'friendships#update'
      delete 'reject_request', to: 'friendships#destroy'
      get 'all_friends', to: 'friends#all_friends'
      get 'show_friend/:friend_id', to: 'friends#show_friend', as: 'show_friend'
    end
end

  # get 'search_friend', to:'friends#search'

  resources :posts do
  member do
    get 'like'
    get 'unlike'
  end
  end

  resources :comments do
    post 'reply', on: :member, to: 'comments#create_reply'
  end

  # Route for showing the profile
  get 'profile', to: 'profiles#show', as: 'profile'

  # Route for updating the profile
  patch 'profile', to: 'profiles#update'

  resource :profile, only: [:show] do
    member do
      patch :update_cover_photo
      patch :update_profile_photo
    end
  end


  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
    root to: 'feeds#index'
  end

  get 'feed', to: 'feeds#index', as: 'feed'

  get 'add_friends', to: 'friends#add_friends'

  # get 'remove_friends', to: 'friends#remove_friends'

end

app/controllers/profiles_controller.rb
# app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @posts = @user.posts.includes(:user, :likes).order(created_at: :desc)
  end

  def update_cover_photo
    @user = current_user
    if @user.update(user_params)
      redirect_to profile_path, notice: 'Cover photo was successfully updated.'
    else
      flash[:alert] = 'There was an error updating the cover photo.'
      render :show
    end
  end

  def update_profile_photo
    @user = current_user
    if @user.update(user_params)
      redirect_to profile_path, notice: 'Profile photo was successfully updated.'
    else
      flash[:alert] = 'There was an error updating the profile photo.'
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:cover_photo, :profile_photo)
  end
end

app/views/profiles/show.html.erb
<div class="container">
  <!-- Display Cover Photo -->
  <div class="cover-photo">
    <% if @user.cover_photo.present? %>
      <%= image_tag @user.cover_photo.url, class: "cover-image", style: "width: 100%; height: auto;" %>
    <% else %>
      <%= image_tag "default_cover_picture.jpg", class: "cover-image", style: "width: 100%; height: auto;" %>
    <% end %>
  </div>

  <!-- Display Profile Photo -->
  <div class="profile-photo">
    <% if @user.profile_photo.present? %>
      <%= image_tag @user.profile_photo.url, class: "img-fluid rounded-circle", style: "width: 150px; height: 150px; margin-left: 30px;" %>
    <% else %>
      <%= image_tag "default_profile_picture.png", class: "img-fluid rounded-circle", style: "width: 150px; height: 150px; margin-left: 30px;" %>
    <% end %>
    <div style="margin-left: 48px">
      <h2 ><%= @user.name %></h2>
      <p><strong><%= link_to "Friends #{@user.friends_count}", all_friends_user_path(@user.id) %></strong> </p>
      <strong>Posts <%=@user.posts_count %> </strong>
    </div>

  </div>

  <div style="margin-left: 900px; margin-bottom: 10px">
  <%= form_for @user, url: update_profile_photo_profile_path, html: { multipart: true } do |f| %>
    <div class="form-group" >
      <%= f.file_field :profile_photo %>
    </div>
    <%= f.submit "Change Profile Photo", class: "btn btn-primary btn-sm" %>

<% end %>
  <%= form_for @user, url: update_cover_photo_profile_path, html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.file_field :cover_photo %>
    </div>
    <%= f.submit "Change Cover Photo", class: "btn btn-primary btn-sm" %>
  <% end %>
    </div>

</div>

<%= link_to "Make a Post", new_post_path, class: "btn btn-primary ", style:"margin-left: 910px"%>

<h2>Posts</h2>
<% @posts.each do |post| %>
  <%= render partial: 'layouts/post', locals: { post: post, current_user: current_user } %>
<% end %>