config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

resources :users, only: [:index, :show] do
    member do
      get 'send_request', to: 'friendships#create'
      get 'accept_request', to: 'friendships#update'
      delete 'reject_request', to: 'friendships#destroy'
      get 'all_friends', to: 'friends#all_friends'
      get 'show_friend/:friend_id', to: 'friends#show_friend', as: 'show_friend'
    end
end

  # get 'search_friend', to:'friends#search'

  resources :posts do
  member do
    get 'like'
    get 'unlike'
  end
  end

  resources :comments do
    post 'reply', on: :member, to: 'comments#create_reply'
  end

  # Route for showing the profile
  get 'profile', to: 'profiles#show', as: 'profile'

  # Route for updating the profile
  patch 'profile', to: 'profiles#update'

  resource :profile, only: [:show] do
    member do
      patch :update_cover_photo
      patch :update_profile_photo
    end
  end


  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
    root to: 'feeds#index'
  end

  get 'feed', to: 'feeds#index', as: 'feed'

  get 'add_friends', to: 'friends#add_friends'

  # get 'remove_friends', to: 'friends#remove_friends'

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_action :set_search_results, only: [:add_friends]

  def all_friends
    @friends = current_user.all_friends
  end

  def add_friends
    # @users = User.all #removed unless current_user == user from view and added logic below
    @users = User.all.reject { |friend| friend == current_user }
  end

  def show_friend
    @user = User.includes(posts: :likes).strict_loading!(mode: :n_plus_one_only).find(params[:friend_id])
  end

  private

  def friend_params
    params.require(:friend).permit(:id)
  end

  def set_search_results
    if params[:query].present?
      @search_results = User.where('name LIKE ?', "%#{params[:query]}%").reject { |user| user == current_user }
    else
      @search_results = []
    end
  end

end

app/views/friends/add_friends.html.erb
<% if @search_results.present? %>
  <h2>Search Results</h2>
  <% @search_results.each do |user| %>
    <%= render partial: 'layouts/user_display', locals: { user: user } %>
  <% end %>
<% end %>

<h2>All Users</h2>
<% @users.each do |user| %>
  <%= render partial: 'layouts/user_display', locals: { user: user } %>
<% end %>

app/views/friends/all_friends.html.erb
<h1>My Friends</h1>
<% @friends.each do |friend| %>
  <p>
    <%= render partial: 'layouts/pic_display', locals: { user: friend } %>
    <%= link_to friend.name, show_friend_user_path(current_user.id, friend_id: friend.id) %>
  </p>
<% end %>

app/views/friends/show_friend.html.erb
<div class="container">
  <!-- Display Cover Photo -->
  <div class="cover-photo">
    <% if @user.cover_photo.present? %>
      <%= image_tag @user.cover_photo.url, class: "cover-image", style: "width: 100%; height: auto;" %>
    <% else %>
      <%= image_tag "default_cover_picture.jpg", class: "cover-image", style: "width: 100%; height: auto;" %>
    <% end %>
  </div>

  <!-- Display Profile Photo -->
  <div class="profile-photo">
    <% if @user.profile_photo.present? %>
      <%= image_tag @user.profile_photo.url, class: "img-fluid rounded-circle", style: "width: 150px; height: 150px; margin-left: 30px;" %>
    <% else %>
      <%= image_tag "default_profile_picture.png", class: "img-fluid rounded-circle", style: "width: 150px; height: 150px; margin-left: 30px;" %>
    <% end %>
    <div style="margin-left: 48px">
      <h2><%= @user.name %></h2>
      <p><strong>Friends <%= @user.friends_count %></strong></p>
      <strong>Posts <%= @user.posts_count %> </strong>
    </div>

  </div>

  <h2>Posts</h2>
  <% @user.posts.each do |post| %>
    <%= render partial: 'layouts/post', locals: { post: post, current_user: current_user } %>
    <%end %>
</div>