config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

resources :users, only: [:index, :show] do
    member do
      get 'send_request', to: 'friendships#create'
      get 'accept_request', to: 'friendships#update'
      delete 'reject_request', to: 'friendships#destroy'
      get 'all_friends', to: 'friends#all_friends'
      get 'show_friend/:friend_id', to: 'friends#show_friend', as: 'show_friend'
    end
end

  # get 'search_friend', to:'friends#search'

  resources :posts do
  member do
    get 'like'
    get 'unlike'
  end
  end

  resources :comments do
    post 'reply', on: :member, to: 'comments#create_reply'
  end

  # Route for showing the profile
  get 'profile', to: 'profiles#show', as: 'profile'

  # Route for updating the profile
  patch 'profile', to: 'profiles#update'

  resource :profile, only: [:show] do
    member do
      patch :update_cover_photo
      patch :update_profile_photo
    end
  end


  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
    root to: 'feeds#index'
  end

  get 'feed', to: 'feeds#index', as: 'feed'

  get 'add_friends', to: 'friends#add_friends'

  # get 'remove_friends', to: 'friends#remove_friends'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :pic, PicUploader

  validates :content, presence: true, length: { maximum: 500 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :set_post_before_destroy, only: [:destroy]

  def index
    @posts = Post.includes(user: :likes)
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to feed_path
    else
      flash[:alert] = "Post could not be saved"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      if request.referer.include?("feed")
        redirect_to feed_path
      else
        redirect_to profile_path
      end
    else
      flash[:alert] = "Post could not be updated"
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Post successfully deleted!"
      redirect_to redirect_path
    else
      flash[:alert] = "Post could not be deleted"
      render json: @post.errors.full_messages
    end
  end

  def like
    @post.likes.create(user: current_user)
    flash[:notice] = "You liked the post"
    redirect_to redirect_path
  end

  def unlike
    @like = @post.likes.find_by(user: current_user)

    if @like
      @like.destroy
      flash[:notice] = "You unliked the post"
    else
      flash[:alert] = "You haven't liked this post"
    end

    redirect_to redirect_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :pic)
  end

  def set_post
    @post = Post.includes(:user, :likes, comments: [:user, replies: :user]).strict_loading!(mode: :n_plus_one_only).find_by(id: params[:id])
    if @post.nil?
      flash[:alert] = "Post not found"
      redirect_to feed_path
    end
  end

  def set_post_before_destroy
    @post = Post.find_by(id: params[:id])
    if @post.nil?
      flash[:alert] = "Post not found"
      redirect_to feed_path
    end
  end

  def redirect_path
    request.referer.include?("profile") ? profile_path : feed_path
  end
end

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for(@post, url: post_path(@post), html: { multipart: true }, method: :patch) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "What's on your mind?" %>
  </div>
  <div class="form-group">
    <%= f.file_field :pic, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h2>Posts Admin Panel</h2>
<% @posts.each do |post| %>
  <div class="post">
    <b><%=current_user.name %></b>
    <small><%= post.created_at.strftime('%d %B %Y at %I:%M %p') %></small>
    <p><%= post.content %></p>
    <% if post.pic.present? %>
      <%= image_tag post.pic.url, class: "post-image", style: "width: 250px; height: 250px; object-fit: cover;"%>
    <% end %>
    <span class="likes-count"><%= post.likes_count %> Likes</span>
    <span class="comments-count"><%= link_to "#{post.comments_count} Comments", post_path(post) %></span>
    <br/>
    <% if current_user && post.user.likes.any? { |like| like.user_id == current_user.id }%>
      <%= link_to "Unlike", unlike_post_path(post), method: :delete, class: "btn btn-danger btn-sm" %>
    <% else %>
      <%= link_to "Like", like_post_path(post), method: :post, class: "btn btn-primary btn-sm" %>
    <% end %>

    <%= link_to "Edit", edit_post_path(post), class: "btn btn-secondary btn-sm" %>
    <%= link_to "Destroy", post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Create a new post</h2>
<%= form_for(@post, url: posts_path) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "What's on your mind?" %>
  </div>
  <div class="form-group">
    <%= f.file_field :pic, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'layouts/post', locals: { post: @post, current_user: current_user } %>

<h3>Comments</h3>
<div id="comments">
  <% @post.comments.each do |comment| %>
    <div class="comment">

      <% if comment.parent_id == nil %>
        <p><strong><%= comment.user.name %></strong> <%= comment.content %></p>
        <% if comment.user == current_user %>
          <%#= link_to "Edit", edit_comment_path(comment, post_id: @post.id), class: "btn btn-primary btn-sm" %>
          <%= link_to "Destroy", comment_path(comment, post_id: @post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "margin-bottom: 10px;" %>
        <% end %>
        <% comment.replies.each do |reply| %>
          <div class="reply" style="margin-left: 20px;">
            <p><strong><%= reply.user.name %></strong> <%= reply.content %></p>
          </div>
        <% end %>
        </div>
        <!-- Reply Form -->
        <div style="margin-left: 20px;">
          <%= form_with model: comment.replies.new, url: reply_comment_path(post_id: @post.id, comment_id: comment.id), class: "reply-form" do |form| %>
            <div>
              <%= form.text_area :content, placeholder: "Reply to #{comment.user.name}..." %>
            </div>
            <div>
              <%= form.submit "Reply", class: "btn btn-primary btn-sm" %>
            </div>
          <% end %>
        </div>

      <% end %>
  <% end %>
</div>

<h3 id="new_comment">Add a Comment</h3>
<%= form_with model: Comment.new, url: comments_path(post_id: @post.id) do |form| %>
  <div>
    <%= form.text_area :content, placeholder: "Your thoughts on this post?" %>
  </div>
  <div>
    <%= form.submit "Comment", class: "btn btn-success btn-sm" %>
  </div>
<% end %>