config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

resources :users, only: [:index, :show] do
    member do
      get 'send_request', to: 'friendships#create'
      get 'accept_request', to: 'friendships#update'
      delete 'reject_request', to: 'friendships#destroy'
      get 'all_friends', to: 'friends#all_friends'
      get 'show_friend/:friend_id', to: 'friends#show_friend', as: 'show_friend'
    end
end

  # get 'search_friend', to:'friends#search'

  resources :posts do
  member do
    get 'like'
    get 'unlike'
  end
  end

  resources :comments do
    post 'reply', on: :member, to: 'comments#create_reply'
  end

  # Route for showing the profile
  get 'profile', to: 'profiles#show', as: 'profile'

  # Route for updating the profile
  patch 'profile', to: 'profiles#update'

  resource :profile, only: [:show] do
    member do
      patch :update_cover_photo
      patch :update_profile_photo
    end
  end


  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
    root to: 'feeds#index'
  end

  get 'feed', to: 'feeds#index', as: 'feed'

  get 'add_friends', to: 'friends#add_friends'

  # get 'remove_friends', to: 'friends#remove_friends'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">

    <a class="navbar-brand font-weight-bold" href='#'>WorkBook</a>

    <% if user_signed_in? %>

      <ul class="navbar-nav ml-auto d-flex flex-row">

        <!-- Search bar -->
        <li class="nav-item ml-auto" style="margin-right: 10px">
          <%= form_with(url: add_friends_path, method: :get, local: true, class: 'form-inline') do %>
            <%= text_field_tag :query, params[:query], placeholder: "Search by name", class: "form-control mr-sm-2" %>
            <%#= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        </li>

        <li class="nav-item mr-3">
          <%= link_to image_tag('icons8-add-friends-50.png', alt: 'Add Friends', class: 'icon-class'), add_friends_path, class: 'nav-link' %>
        </li>

        <li class="nav-item mr-3">
          <%= link_to image_tag('icons8-feed-30.png', alt: 'Feed', class: 'icon-class'), feed_path, class: 'nav-link' %>
        </li>

        <li class="nav-item mr-3">
          <%= link_to image_tag('icons8-male-user-48.png', alt: 'User Profile', class: 'icon-class'), profile_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Logout', sign_out_path, method: :delete, class: 'nav-link', data: { turbo_method: :delete, confirm: "Are you sure you want to log out?" } %>
        </li>
      </ul>
    <% else %>
      <!-- Display these links when user is not logged in -->
      <ul class="navbar-nav ml-auto">
        <% if current_page?(new_user_registration_path) %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        <% elsif current_page?(new_user_session_path) %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_pic_display.html.erb
<% if user.profile_photo.present? %>
  <%= image_tag user.profile_photo.url, class: "img-fluid rounded-circle", style: "width: 35px; height: 35px;" %>
<% else %>
  <%= image_tag "default_profile_picture.png", class: "img-fluid rounded-circle", style: "width: 35px; height: 35px; margin-right:5px;" %>
<% end %>

app/views/layouts/_post.html.erb
<div class="post" style="margin-bottom: 10px;">
  <%= render partial: 'layouts/pic_display', locals: { user: post.user } %>
  <b><%= post.user.name %></b>
  <small>Posted <%= time_ago_in_words(post.created_at) %> ago</small>
  <p><%= post.content %></p>
  <% if post.pic.present? %>
    <%= image_tag post.pic.url, class: "post-image", style: "width: 250px; height: 250px; object-fit: cover;" %>
  <% end %>
  <p><strong><%= post.likes_count %></strong> Likes |
    <strong><%= link_to "#{post.comments_count} Comments", post_path(post) %></strong></p>

  <% if current_user && post.likes.any? { |like| like.user_id == current_user.id } %>
    <%= link_to "Unlike", unlike_post_path(post), method: :delete, class: "btn btn-danger btn-sm" %>
  <% else %>
    <%= link_to "Like", like_post_path(post), method: :post, class: "btn btn-primary btn-sm" %>
  <% end %>

  <% if post.user == current_user %>
    <%= link_to "Edit", edit_post_path(post), class: "btn btn-secondary btn-sm" %>

    <%= link_to "Destroy", post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
  <% end %> </div>

app/views/layouts/_user_display.html.erb
<div style="display: flex; align-items: center; margin-bottom: 10px;">
  <%= render partial: 'layouts/pic_display', locals: { user: user } %>
  <strong style="flex: 1;"><%= user.name %></strong>
  <div>
    <% friendship = current_user.friendships.find { |f| f.friend_id == user.id } %>
    <% inverse_friendship = current_user.inverse_friendships.find { |f| f.user_id == user.id } %>
    <% if friendship && friendship.status == 'pending' %>
      <%= link_to 'Withdraw Friend Request', reject_request_user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-secondary btn-sm", style: "margin-left: 10px;" %>
    <% elsif (friendship && friendship.status == 'accepted') || (inverse_friendship && inverse_friendship.status == 'accepted') %>
      <%= link_to 'Remove Friend', reject_request_user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "margin-left: 10px;" %>
    <% elsif inverse_friendship && inverse_friendship.status == 'pending' %>
      <%= link_to "Accept Friend Request", accept_request_user_path(user), method: :patch, class: "btn btn-primary btn-sm", style: "margin-left: 10px;" %>
      <%= link_to 'Reject Friend Request', reject_request_user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "margin-left: 10px;" %>
    <% else %>
      <%= link_to "Send Friend Request", send_request_user_path(user), method: :post, class: "btn btn-primary btn-sm", style: "margin-left: 10px;" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
    <head>
      <title>WorkBook</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

      <!-- Application CSS -->
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
    </head>

    <body>
    <!-- Navbar -->
    <%= render 'layouts/navbar' %>

    <div class="container mt-4">
      <!-- Flash Messages -->
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <!-- Main Content -->
      <%= yield %>
    </div>

    <!-- Bootstrap Bundle with Popper (for JavaScript components) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Custom Script to auto-dismiss flash messages after a few seconds -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            setTimeout(() => {
                const alerts = document.querySelectorAll('.alert');
                alerts.forEach(alert => {
                    const bsAlert = new bootstrap.Alert(alert);
                    bsAlert.close();
                });
            }, 5000); // Adjust time (in milliseconds) as needed
        });
    </script>
    </body>
    </html>